name: raven_player
description: "Raven Player - a sleek, feature-rich offline audiobook player built with Flutter."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.11.5

dependencies:
  audio_video_progress_bar: ^2.0.3
  build_runner: ^2.15.0
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.4.7

  #? State Management
  flutter_riverpod: ^3.3.1

  flutter_slidable: ^4.0.3
  hive_ce: ^2.19.3
  hive_ce_flutter: ^2.3.4
  hive_ce_generator: ^1.11.1
  just_audio: ^0.10.5
  logger: ^2.7.0
  lottie: ^3.3.3
  marquee: ^2.3.0
  path_provider: ^2.1.5
  rxdart: ^0.28.0
  skeletonizer: ^2.1.3
  synchronized: ^3.4.0+1

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/animations/
    - assets/app/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-Medium.ttf
        - asset: assets/fonts/Inter-Bold.ttf
          style: normal

#? Splash
flutter_native_splash:
  android: true
  ios: true
  web: false

  color: "#000000"
  image: "assets/app/splash.png"

  android_12:
    color: "#000000"
    image: "assets/app/logo_android.png"
    branding: "assets/app/branding_android.png"
