name: raven_player
description: "Raven Player - a sleek, feature-rich offline audiobook player built with Flutter."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any

  #? State Management
  flutter_riverpod: ^3.3.1

  #? Storage / Persistence
  hive_ce: ^2.19.3
  hive_ce_flutter: ^2.3.4

  #? Audio
  just_audio: ^0.10.5
  audio_service: ^0.18.18
  rxdart: ^0.28.0

  #? UI
  audio_video_progress_bar: ^2.0.3
  flutter_slidable: ^4.0.3
  font_awesome_flutter: ^11.0.0
  lottie: ^3.3.3
  marquee: ^2.3.0
  skeletonizer: ^2.1.3

  #Pin the version:
  # https://github.com/timmaffett/material_symbols_icons/issues/46
  material_symbols_icons: 4.2906.0

  #? Platform / Device
  flutter_app_minimizer_plus: ^1.0.2
  package_info_plus: ^10.1.0
  path_provider: ^2.1.5
  shake: ^3.0.0
  url_launcher: ^6.3.2

  #? Utilities
  crypto: ^3.0.7
  logger: ^2.7.0
  synchronized: ^3.4.0+1

  #? Launcher
  flutter_native_splash: ^2.4.7
  flutter_launcher_icons: ^0.14.4

dev_dependencies:
  #? Code Generation
  build_runner: ^2.15.0
  hive_ce_generator: ^1.11.1

  #? Lints
  flutter_lints: ^6.0.0

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/docs/en/
    - assets/docs/pl/
    - assets/animations/
    - assets/launcher/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700

#? Splash
flutter_native_splash:
  android: true
  ios: true
  web: false

  color: "#000000"
  image: "assets/app/splash.png"

  android_12:
    color: "#000000"
    image: "assets/app/logo_android.png"
    branding: "assets/app/branding_android.png"
